apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: adhoc-admin

components:
  - ../helper-job

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patch-job.yaml
    target:
      kind: Job
      name: adhoc-admin-helper
