apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: adhoc-admin

components:
  - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/cluster-configs/adhoc-admin/components/helper?ref=main
  - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/cluster-configs/adhoc-admin?ref=main

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: demo-adhoc
    files:
      - scripts/00-adhoc.sh

patches:
  - path: patch-job.yaml
    target:
      kind: Job
      name: adhoc-admin-helper
