apiVersion: batch/v1
kind: Job
metadata:
  name: adhoc-admin-helper
spec:
  template:
    spec:
      containers:
        - name: minion
          env:
            - name: ADHOC_DIR
              value: /scripts/custom
          volumeMounts:
            - name: custom
              mountPath: /scripts/custom
      volumes:
        - name: custom
          configMap:
            name: demo-adhoc
            defaultMode: 0755
