apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../module/local/cluster-configs/branding
  - ../../module/local/cluster-configs/helper-job-custom
  - ../../module/remote/cluster-configs/login
  - ../../module/local/cluster-configs/no-self-provisioner
  
  - ../../module/local/operators/web-terminal
