apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/cluster-configs/rbac/overlays/no-self-provisioner?ref=v0.17
