apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  annotations:
    controller.devfile.io/allow-import-from: '*'
    web-terminal.redhat.com/unmanaged-state: 'true'
  name: web-terminal-tooling
  namespace: openshift-operators
  labels:
    console.openshift.io/terminal: 'true'
spec:
  components:
    - container:
        args:
          - "/bin/bash"
          - "-c"
          - |
            #!/bin/bash

            echo "
            GIT_REPO=https://github.com/redhat-na-ssa/demo-ocp-template.git
            GIT_PATH=demo

            [ -e ~/\${GIT_PATH} ] || git clone \${GIT_REPO} ~/\${GIT_PATH}
            [ -e ~/\${GIT_PATH} ] && cd ~/\${GIT_PATH}

            " >> /home/user/.bashrc

            . /home/user/.bashrc

            sleep infinity  # just in case

        cpuLimit: 400m
        cpuRequest: 100m
        image: ghcr.io/redhat-na-ssa/web-terminal-tooling:latest
        memoryLimit: 512Mi
        memoryRequest: 128Mi
        mountSources: false
        sourceMapping: /projects
      name: web-terminal-tooling
