---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - job.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: adhoc-admin-helper
    # namespace: adhoc-admin
    files:
      - job.sh
